name: Split Monorepo (Monoplus POC)

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
    workflow_dispatch: ~

jobs:
    split_monorepo:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false

        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Monorepo Split of CoreBundle
                uses: alphpaca/monoplus-split-action@2022.1-alpha6
                with:
                    package_path: 'src/Sylius/Bundle/CoreBundle'
                    personal_access_token: ${{ secrets.MONOPLUS_PAT }}
                    git_username: 'jakubtobiasz'
                    git_email: 'jakub.tobiasz@icloud.com'
                    repository_owner: "jakubtobiasz"
                    repository_name: "MonoplusSyliusCoreBundle"
